development:
  adapter: postgresql
  encoding: utf8
  database: project_development
  pool: 5
  username:
  password: 
  host: localhost
  port: 5432

test:
  adapter: postgresql
  encoding: utf8
  database: project_test
  pool: 5
  username:
  password: 
  host: localhost
  port: 5432

